runtime: python39  # Python 3.9
entrypoint: gunicorn -b :$PORT app:app

env_variables:
  OPENWEATHER_API_KEY: your_openweather_api_key
  GEMINI_API_KEY: your_gemini_api_key
  GOOGLE_MAPS_API_KEY: your_google_maps_api_key

handlers:
  - url: /.*
    script: auto
